Repository mopidy/mopidy-spotify, pull requests merged in 2019-12, with the labels that each got.

#235 Web API playlists v3
  CHANGELOG.rst
  README.rst
  mopidy_spotify/__init__.py
  mopidy_spotify/backend.py
  mopidy_spotify/browse.py
  mopidy_spotify/distinct.py
  mopidy_spotify/library.py
  mopidy_spotify/lookup.py
  mopidy_spotify/playback.py
  mopidy_spotify/playlists.py
  mopidy_spotify/search.py
  mopidy_spotify/translator.py
  mopidy_spotify/utils.py
  mopidy_spotify/web.py
  tests/conftest.py
  tests/test_backend.py
  tests/test_browse.py
  tests/test_distinct.py
  tests/test_images.py
  tests/test_lookup.py
  tests/test_playback.py
  tests/test_playlists.py
  tests/test_search.py
  tests/test_translator.py
  tests/test_web.py
Labels: web api

#237 Use Web API for personal top tracks and artists.
  CHANGELOG.rst
  README.rst
  mopidy_spotify/browse.py
  mopidy_spotify/library.py
  mopidy_spotify/translator.py
  tests/test_browse.py
  tests/test_translator.py
Labels: web api

#239 Return WebResponse even in error cases.
  mopidy_spotify/web.py
  tests/test_web.py
Labels: bug, web api

#238 Support browsing of albums and tracks from the "Your music" library
  CHANGELOG.rst
  README.rst
  mopidy_spotify/browse.py
  mopidy_spotify/translator.py
  tests/test_browse.py
  tests/test_translator.py
Labels: enhancement, web api

#243 Add support for playlist images from webapi
  mopidy_spotify/images.py
  tests/test_images.py
Labels: web api

#245 Follow linked-from to get id in image fetching (fixes #171)
  mopidy_spotify/images.py
  tests/test_images.py
Labels: bug, web api

#248 Valid web object must not be None (Fixes #246)
  mopidy_spotify/translator.py
  tests/test_translator.py
Labels: A-webapi, C-bug

#247 Feature/featured playlists
  mopidy_spotify/browse.py
  mopidy_spotify/playlists.py
  mopidy_spotify/translator.py
  tests/conftest.py
  tests/test_browse.py
  tests/test_translator.py
Labels: A-webapi, C-enhancement
